services:
  crawler-worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    environment:
      TZ: Asia/Ho_Chi_Minh
